base="dark"
primaryColor="#00BFA6"              # Verde menta elegante
backgroundColor="#121212"           # Fondo negro moderno
secondaryBackgroundColor="#1E1E1E"  # Paneles y tarjetas
textColor="#FFFFFF"                 # Texto blanco
font="sans serif"
